language: node_js
node_js: "10"

addons:
  chrome: stable

cache: yarn

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

before_install:
  - npm install -g @lhci/cli

install:
  - yarn

jobs:
  include:
    - stage: build
      name: Build core
      script:
        - yarn build:core

    - stage: build
      name: Build prismic
      script:
        - yarn build:core
        - yarn build:prismic

    - stage: build
      name: Build commercetools
      script:
        - yarn build:ct

    - stage: build
      name: Build about you
      script:
        - yarn build:ayc

    - stage: build
      name: Lint
      script:
        - yarn lint

    - stage: unit tests
      script: yarn test:core --coverage
      name: Test core packages
      after_script:
        - cat ./packages/core/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ct:api-client --coverage
      name: Test CT api-client
      after_script:
        - cat ./packages/commercetools/api-client/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ct:composables --coverage
      name: Test CT composables
      after_script:
        - cat ./packages/commercetools/composables/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ayc:api-client --coverage
      name: Test AY api-client
      after_script:
        - cat ./packages/about-you/api-client/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn build:ayc:api-client && yarn test:ayc:composables --coverage
      name: Test AY composables
      after_script:
        - cat ./packages/about-you/composables/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:prismic --coverage
      name: Test Prismic
      after_script:
        - cat ./packages/prismic/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:cli --coverage
      name: Test CLI
      after_script:
        - cat ./packages/core/cli/coverage/lcov.info | coveralls

    # - stage: lighthouse
    #   name: commercetools
    #   script: lhci autorun --rc-overrides.upload.target=temporary-public-storage --collect.startServerCommand="yarn start:ct" --collect.url=http://localhost:3000 --collect.startServerReadyPattern="Listening"
