language: node_js
node_js: "10"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - packages/commercetools/api-client/node_modules
    - packages/commercetools/api-client/lib
    - packages/commercetools/helpers/node_modules
    - packages/commercetools/helpers/lib
    - packages/commercetools/composables/node_modules
    - packages/commercetools/composables/lib
    - packages/commercetools/theme/.nuxt
    - packages/commercetools/theme/node_modules
    - packages/about-you/api-client/node_modules
    - packages/about-you/api-client/lib
    - packages/about-you/composables/node_modules
    - packages/about-you/composables/lib
    - packages/core/core/node_modules
    - packages/core/core/lib
    - packages/prismic/node_modules
    - packages/prismic/lib

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

before_install:
  - npm install -g @lhci/cli

install:
  - yarn
  - yarn link-packages

jobs:
  include:
    - stage: build
      name: Build commercetools
      script:
        - yarn build:prismic && yarn build:ct

    - stage: build
      name: Build about you
      script:
        - yarn build:ayc

    - stage: unit tests
      script: yarn test:core --coverage
      name: Test core packages
      after_script:
        - cat ./packages/core/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ct:api-client --coverage
      name: Test CT api-client
      after_script:
        - cat ./packages/commercetools/api-client/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ct:composables --coverage
      name: Test CT composables
      after_script:
        - cat ./packages/commercetools/composables/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:ayc:api-client --coverage
      name: Test AY api-client
      after_script:
        - cat ./packages/about-you/api-client/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn build:ayc:api-client && yarn test:ayc:composables --coverage
      name: Test AY composables
      after_script:
        - cat ./packages/about-you/composables/coverage/lcov.info | coveralls

    - stage: unit tests
      script: yarn test:prismic --coverage
      name: Test Prismic
      after_script:
        - cat ./packages/prismic/coverage/lcov.info | coveralls

    # - stage: lighthouse
    #   name: commercetools
    #   script: lhci autorun --rc-overrides.upload.target=temporary-public-storage --collect.startServerCommand="yarn start:ct" --collect.url=http://localhost:3000 --collect.startServerReadyPattern="Listening"

    - build_image:
      if: branch = master AND type != pull_request
      name: "Build docker image"
      stage: docker build
      script:
        - travis_wait 30 docker build --build-arg COMMIT -t registry.storefrontcloud.io/vsf-next-demo-storefrontcloud-io/vue-storefront:$COMMIT -f dev/docker/Dockerfile .
        - echo $DOCKER_PASSWORD | docker login  -u="$DOCKER_USERNAME" --password-stdin registry.storefrontcloud.io
        - docker push registry.storefrontcloud.io/vsf-next-demo-storefrontcloud-io/vue-storefront:$COMMIT
        - curl $COMMIT.vsf-next-demo.preview.storefrontcloud.io
        - echo "This commit preview is available here $COMMIT.vsf-next-demo.preview.storefrontcloud.io"

    - deploy_to_storefrontcloud:
      if: branch = master AND type != pull_request
      name: "Deploy to StorefrontCloud"
      stage: deploy
      script:
        - "curl -u $CLOUD_USERNAME:$CLOUD_PASSWORD -H 'Content-Type: application/json' -X POST -d \"{\\\"code\\\":\\\"vsf-next-demo\\\", \\\"frontContainerVersion\\\":\\\"$COMMIT\\\"}\" https://farmer.storefrontcloud.io/instances"
