sudo: required
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - &build
      stage: Build
      script:
        - yarn lint
        - yarn build
      node_js: "10"

    - &unit
      stage: Test
      script: yarn test:unit
      name: "NodeJS 10 unit tests"
      node_js: "10"


    - &installer
      script: yarn installer:ci
      name: "NodeJS 10 installer test"
      if: branch IN (master, develop)
      node_js: "10"
      addons:
        chrome: stable


