version: '2.0'
services:
  app:
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    environment:
      - VS_ENV
      - NODE_CONFIG_ENV=docker
      - PM2_ARGS=--no-daemon
      - HELMET_ENABLED
      - HELMET_FRAME_ANCESTORS

      - NODEJS_INSTANCES_COUNT
      - NODEJS_INSTANCE_MAX_MEMORY
      - NODEJS_INSTANCE_MAX_OLD_SPACE

      - SSR_USE_HTML_MINIFIER

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

      - DEFAULT_STORE_ID
      - DEFAULT_STORE_CODE
      - DEFAULT_STORE_TITLE=${DEFAULT_STORE_NAME}
      - DEFAULT_STORE_NAME
      - DEFAULT_STORE_DESCRIPTION
      - STORE_THEME

      - VSF_API_DOMAIN
      - CACHE_INVALIDATION_KEY
      - FILEUPLOADER_UPLOAD_URL
      - IMAGE_HANDLER_SERVICE_URL
      
      - GTM_ID
      
      - AFFIRM_PUBLIC_KEY
      - AFFIRM_CDN
      
      - AMAZONPAY_SANDBOX
      - AMAZONPAY_SELLER_ID
      - AMAZONPAY_CLIENT_ID

      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - './config/local.json.template:/var/www/config/local.json.template'
      - './babel.config.js:/var/www/babel.config.js'
      - './core:/var/www/core'
      - './ecosystem.json.template:/var/www/ecosystem.json.template'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig-build-dev.json:/var/www/tsconfig-build-dev.json'
      - './tsconfig-build.json:/var/www/tsconfig-build.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
      - './packages:/var/www/packages'
      - './node_modules:/var/www/node_modules'
      - './yarn.lock:/var/www/yarn.lock'
      - cache://usr/local/share/.cache
    tmpfs:
      - /var/www/dist
    networks:
      - default
      - reverseproxy
      # - vue-storefront-api
    expose:
      - 3000

volumes: 
  cache:

networks:
  reverseproxy:
      name: webdevelopmentreverseproxy_default
#  vue-storefront-api:
#    external:
#      name: vue-storefront-api_default
