name: VSF Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  release-packages:
    name: "Release NPM Packages"
    uses: vuestorefront/vue-storefront/.github/workflows/cd-integrations.yml@main
    secrets: inherit
    with:
      enterprise: false
