name: Run E2E Regression Tests
on:
  schedule:
    - cron: "0 0 * * 1-5"
jobs:
  run_e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["ct", "bp"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarn build:${{ matrix.package }}
        env:
          NUXT_ENV_E2E: true

      - name: Run cypress tests
        uses: cypress-io/github-action@v2.8.2
        with:
          start: yarn start:${{ matrix.package }}
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          command: yarn run test:e2e:${{ matrix.package }}:hl
          browser: chrome
          headless: true
          install: false
        env:
          CYPRESS_INCLUDE_TAGS: regression

      - name: Generate report
        if: ${{ always() }}
        run: yarn test:e2e:${{ matrix.package }}:generate:report

      - name: Upload bp report artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: report-bp
          path: "packages/boilerplate/theme/tests/e2e/report"
          if-no-files-found: ignore

      - name: Upload ct report artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: report-ct
          path: "packages/commercetools/theme/tests/e2e/report"
          if-no-files-found: ignore
